<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Etape2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>93c781dd-9b8b-4bab-a441-6968bdb65dbd</testSuiteGuid>
   <testCaseLink>
      <guid>086fceb3-4828-45f9-a076-687d28a46865</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Etape2/Partenaire</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81091883-060b-44ce-b98b-a8cd106774aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa0c3e9b-b65f-4993-9eba-c31b286d00ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1149416b-f4e3-4fbf-8a2b-8634efe306b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7af4b44-a750-44bd-a55d-8487d816cf37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b13525d9-0de9-4ee9-8484-3a2541ee39eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ec84c2f-466f-4c5b-882d-9857e32f7b4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd7a7fd7-39d7-4c7f-90ef-c9066e33b6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdcacddc-b8c1-452a-9972-fd8d098d5585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a5fb4bc-3965-4543-9b71-005361c65ad6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1522c46d-67cc-439c-a2b7-00ffaef20370</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Etape2/Création projet</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>49868248-b70f-4afa-81d7-5dcc327600b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Etape2/Création IA</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d9bfc20a-284d-4672-a2cb-f43492da86b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Etape2/Facturation</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
