<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date de naissance_birthDate</name>
   <tag></tag>
   <elementGuidId>7804f758-1855-4b08-ad62-59633eb3280b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;birthDateControl&quot;)[count(. | //input[@type = 'text' and @class = 'form-control ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty myiad-form-node-control ng-valid-date' and @id = 'birthDateControl' and @name = 'birthDate' and @placeholder = 'dd/mm/yyyy' and @ng-class = '::$node.attrs.mixStyles()' and @ng-model = '$node.attrs.model[$node.attrs.name]' and @ng-change = '::$node.attrs.onChange($node.attrs.model[$node.attrs.name])' and @ng-focus = '::$node.setAttrs({ isCalendarOpened: true })' and @ng-disabled = '$node.attrs.isDisabled' and @is-open = '$node.attrs.isCalendarOpened' and @on-open-focus = 'false' and @show-button-bar = 'false' and @popup-placement = 'bottom-left' and @datepicker-options = '::$node.attrs.calendarOptions' and @uib-datepicker-popup = 'dd/MM/yyyy' and @iad-input-constraints = '$node.attrs.constraints']) = count(//input[@type = 'text' and @class = 'form-control ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty myiad-form-node-control ng-valid-date' and @id = 'birthDateControl' and @name = 'birthDate' and @placeholder = 'dd/mm/yyyy' and @ng-class = '::$node.attrs.mixStyles()' and @ng-model = '$node.attrs.model[$node.attrs.name]' and @ng-change = '::$node.attrs.onChange($node.attrs.model[$node.attrs.name])' and @ng-focus = '::$node.setAttrs({ isCalendarOpened: true })' and @ng-disabled = '$node.attrs.isDisabled' and @is-open = '$node.attrs.isCalendarOpened' and @on-open-focus = 'false' and @show-button-bar = 'false' and @popup-placement = 'bottom-left' and @datepicker-options = '::$node.attrs.calendarOptions' and @uib-datepicker-popup = 'dd/MM/yyyy' and @iad-input-constraints = '$node.attrs.constraints'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthDateControl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty myiad-form-node-control ng-valid-date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthDateControl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>::$node.attrs.mixStyles()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$node.attrs.model[$node.attrs.name]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>::$node.attrs.onChange($node.attrs.model[$node.attrs.name])</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>::$node.setAttrs({ isCalendarOpened: true })</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$node.attrs.isDisabled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>$node.attrs.isCalendarOpened</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>on-open-focus</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>show-button-bar</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>popup-placement</name>
      <type>Main</type>
      <value>bottom-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-options</name>
      <type>Main</type>
      <value>::$node.attrs.calendarOptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-datepicker-popup</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iad-input-constraints</name>
      <type>Main</type>
      <value>$node.attrs.constraints</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthDateControl&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthDateControl']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1139-7239-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-identity-form/div/div/div[2]/div/iad-form-group/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/iad-form-group/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
