<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ajouter un email_fa fa-plus</name>
   <tag></tag>
   <elementGuidId>c817b4ce-2017-4957-afb5-d508f6904001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1144-9880-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-information-address-form/ng-form/iad-block[2]/section/div/iad-block-body/iad-my-iad-add-remove-extended/div/div/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iad-my-iad-add-remove-extended[@items = '$ctrl.contact.emails' and @button-title = '$ctrl.emailButtonTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iad-my-iad-add-remove-extended</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>items</name>
      <type>Main</type>
      <value>$ctrl.contact.emails</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>button-title</name>
      <type>Main</type>
      <value>$ctrl.emailButtonTitle</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1144-9880-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-my-iad-contact-information-address-form/ng-form/iad-block[2]/section/div/iad-block-body/iad-my-iad-add-remove-extended/div/div/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iad-block[2]/section/div/iad-block-body/iad-my-iad-add-remove-extended/div/div/button/span</value>
   </webElementXpaths>
</WebElementEntity>
