<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FRANCE</name>
   <tag></tag>
   <elementGuidId>33576dd8-3b15-46cd-b9f2-7e79ce819502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'FRANCE' or . = 'FRANCE')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/div[1]/iad-agent[1]/main[1]/div[1]/div[1]/iad-agent-my-iad[1]/div[1]/iad-content[1]/div[1]/div[1]/div[2]/iad-content-body[1]/iad-agent-my-iad-contact[1]/ui-view[1]/iad-agent-my-iad-contact-create-page[1]/form[1]/iad-my-iad-accordion[1]/uib-accordion[1]/div[1]/div[1]/div[1]/div[2]/div[1]/iad-my-iad-accordion-group-body[1]/div[1]/ng-transclude[1]/div[1]/iad-my-iad-contact-identity-form[1]/div[1]/div[1]/div[2]/div[3]/iad-form-group[1]/div[1]/div[1]/ul[1]/li[1]/div[3]/span[1]/span[1]/span[1]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>item.label | highlight: $select.search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-select-highlight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FRANCE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='ui-select-choices-row-25-0']//span[@class='ui-select-highlight'][contains(text(),'FRAN')]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choisir'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationalité'])[1]/following::span[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CE']/parent::*</value>
   </webElementXpaths>
</WebElementEntity>
